### ISSUE TITLE
[Webpack] File Loaders cause mocha to throw Syntax Error

### ISSUE THREAD

**Issue by pl12133** [bruderstein/unexpected-react#1]
I went to integrate this test setup into my project which is built on Webpack. As such my `.js` files sometimes include files loaded with webpack loaders; for example `.png` or `.scss`. Mocha throws a `SyntaxError` on encountering these, so you need a custom compiler.

My custom compiler `src/tests/compiler.js`:

    'use strict'
    var babel = require('babel-core/register');
    function noop() {
        return null;
    }
    require.extensions['.scss'] = noop;
    require.extensions['.css'] = noop;

And new `npm test` command:

    mocha --compilers js:./src/tests/compiler.js ./src/tests/*.spec.js

**Comment by bruderstein** [comment]
Thanks for reporting the fix! I've added your text to the wiki, so hopefully people can find it if they need it.

**Comment by mattdell** [comment]
+1

Helped me solve what I thought was a fairly obscure issue.

**Comment by siawyoung** [comment]
+1, saved my life

**Comment by mrberggg** [comment]
Thanks for posting this, saved me!

**Comment by pl12133** [comment]
**Update:** There is now a package called [ignore-styles](https://www.npmjs.com/package/ignore-styles) which seems to accomplish the same goals and also may help with testability.

**Comment by ctountzis** [comment]
+1

**Comment by rewmike** [comment]
+1

**Comment by Qquanwei** [comment]
+1
