### ISSUE TITLE
Seems to be generating some stray promises

### ISSUE THREAD

**Issue by mhintz** [bruderstein/unexpected-react#10]
Hello!

First off, thanks for your hard work on this library! It seems awesome, and just what we need to get started really testing our React apps.

I'm working on setting up a test running environment, and I'm running across a strange problem when executing unexpected-react assertions in a browser environment. My setup is: unexpected-react + Mocha + Karma + Webpack.

The problem show ups when returning unexpected-react's `'to have rendered'` assertion to a mocha wrapper function. It looks like in Chrome, the Promises are never being resolved, while in Safari and Firefox, it's generating extra promises which are outside of the promise chain. I'm getting the bluebird.js warning [documented here](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it). Curiously, in the PhantomJS environment, everything seems to work fine.

I'm running these browser/os versions:
Mac OS X 10.10.5
PhantomJS 2.1.1
Chrome 47.0.2526
Firefox 41.0.0
Safari 9.0.3

I'm hoping, with your deeper understanding of the code base, and of the way unexpected generates promises, you might be able to shed some light on the issue.

I've made a gist test case which demonstrates the issue:

https://gist.github.com/mhintz/d85516a1ba8415bc4deb

Should work with `npm install && npm run test`

Thanks a lot for any advice you can give!

**Comment by bruderstein** [comment]
Hi, and thanks for the great bug report.

I just wanted to comment so you know I've seen it, but I probably won't get chance to investigate until early next week.

I'm stoked it works at all - I've not been able to/had chance to test it in browser. Make sure your react devtools are disabled in the browser(s) you're running karma in, otherwise kittens die and stuff. 😀

**Comment by mhintz** [comment]
You're welcome! We really liked the blog post you wrote, and it convinced us to give `unexpected-react` a shot. I've been working with it extensively the past couple of days implementing component tests. Everything runs fine in PhantomJS (I'm not sure why), but in the browser environment, the warnings/errors start to pop up. No idea why Chrome would behave differently from Safari and Firefox, though!

**Comment by papandreou** [comment]
Could you please try again with Unexpected 10.8.1? Unfortunately 10.7.0 and 10.8.0 included a not fully integrated Bluebird update that caused symptoms like these in Blink-based browsers.

I still haven't figured out exactly what went wrong, but will make sure to get to the bottom of it before re-attempting the update :)

**Comment by bruderstein** [comment]
I can't try this yet, but this sounds really hopeful. I've got so far that I can see which promise bluebird thinks has been forgotten, but it hasn't. It's returned. I've been trying to trace down how it thinks that it's a "forgotten" promise, but not got far enough to say anything concrete. I'll try it later tonight. 

Many thanks @papandreou for chiming in!

**Comment by mhintz** [comment]
I updated the unexpected version to `10.8.1`, and it's working like a charm now! My example posted above works fine, without any warnings, and my actual test suite, which makes more extensive use of `unexpected-react`, is running successfully with no warnings on PhantomJS, Chrome, Safari, and Firefox (OS X).

Thanks for the tip, @papandreou!

**Comment by mhintz** [comment]
Btw, it might make sense to update the `unexpected` version in `package.json` to `10.8.1`

**Comment by bruderstein** [comment]
Confirmed this works for me too. I'm so relieved :)

Thanks again @papandreou
