### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by yormi** [bruderstein/unexpected-react#14]
Hi there !

I'm trying to figure what is the problem with this code. I'm I forgetting something or it is supposed to work ?

(EDIT: I made a minimalistic example and I realize it's the sibbling-element, here the button, that make the test fail. So is there a way to test that a certain element is in the given DOM no matter wrapper-sibblings-children with unexpected-react or should I use something else. Something like: `assert.ok(findRenderedDOMComponentWithClass(...)` which is annoying if I don't want to give it a `className` just for testing purposes)

```javascript
class TestComponent extends React.Component {
  render () {
    return (
      <div>
        <button>Something else</button>
        <p>{this.props.str}</p>
      </div>
    )
  }
}

it.only('TEST', function () {
  const someString = 'Banana'
  let component

  try {
    component = renderIntoDocument(<TestComponent str={someString} />)
  } catch (err) {
    console.log(err)
  }
  return expect(component, 'to have rendered', <p>{someString}</p>)
})
```
(`<p><em>Joe</em></p>` has the same problem but not `<HeaderComponent currentUser
Since I get this error...

```html
     UnexpectedError: 
expected
<TestComponent str="Banana">
  <div><button>Something else</button><p>Banana</p></div>
</TestComponent>
to have rendered <p>Banana</p>

<TestComponent // should be <p
   str="Banana">
  <div>
    <button>Something else</button>
    <p>
      Banana
    </p>
  </div>
</TestComponent>
```

A million thanks for the project btw. Very useful :)

**Comment by sunesimonsen** [comment]
Have you tried 'to contain'?

**Comment by bruderstein** [comment]
Yes, I think @sunesimonsen is right, and `to contain` is the answer here.

And a wrapper and a sibling doesn't work, I'm not sure if it should.... probably following the rules we've set.

If `to contain` solves your problem, we'll close this issue, but I'll see if we can make sibling and wrappers to work.

**Comment by yormi** [comment]
Oh I missed the `to contain` assertion. Bad me... I thought there were just the `to have rendered` family.

I'll let you guys decide if `to have rendered` should support the sibblings in a wrapper but if not, maybe juste adding a note to the doc saying to use `to contain` in that case may save some time to others :)

Cheers :D
