### ISSUE TITLE
Symbol requires babel-polyfill

### ISSUE THREAD

**Issue by janmeier** [bruderstein/unexpected-react#18]
When running tests that use unexpected-react on karma + saucelabs we get the following error:

```js
IE 11.0.0 (Windows 8.1 0.0.0) ERROR
  'Symbol' is undefined
  at /home/ubuntu/frontend/app/tests.webpack.js:40560 <- webpack:///~/unexpected-react/lib/deepAssertions.js:30:0
```

I've fixed it by adding babel-polyfill to our karma entry-point, but shouldn't this library include the polyfill in its babel config?

**Comment by bruderstein** [comment]
Yes. 

Actually, better would be to remove the need for a symbol here. It's probably "the right way" to do it with symbol available, but where it isn't we can just use a simple object as a uniquely identifiable entity.

**Comment by janmeier** [comment]
Sweet, thanks for the quick response and fix! :)
