### ISSUE TITLE
Sibling elements messes with 'to have rendered' assertion

### ISSUE THREAD

**Issue by janmeier** [bruderstein/unexpected-react#21]
Assuming I have a component that renders two form elements, each inside its own nested div:

```js
class Tester extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      country: 'DK'
    };
  }
  render() {
    return (
      <form>
        <div className="form-group col-md-6">
          <label htmlFor="country" className="control-label">Country *</label>
          <select value={this.state.country} >
            <option value="AF">Afghanistan</option>
            <option value="DK">Denmark</option>
          </select>
        </div>
        <div className="form-group col-md-6">
          <label htmlFor="country" className="control-label">Name *</label>
          <input className="form-control" />
        </div>
      </form>
    );
  }
}
```

I shallow render them, and want to test that the select has the correct value

```js
this.renderer.render(<Tester />);

expect(
  this.renderer,
  'to have rendered',
  <form>
    <select value="DK" />
  </form>
);
```

If there is only one element (the select and its wrapper), the test passes, but when there are two elements (as shown in the example), in get the following error:

![image](https://cloud.githubusercontent.com/assets/1210224/14532215/930dd9ea-0260-11e6-8117-05217d78e2cc.png)

I have tested both shallow and deep rendering, and the `have rendered` and `contains` assertions, and they all give me the same error.

Am I unexpecting too much magic from the library, or should this kind of assertion be supported?

**Comment by janmeier** [comment]
Oh, and thanks for an awesome library by the way! :)

**Comment by bruderstein** [comment]
It's certainly a currently unsupported form. I *think* supporting it would be too expensive, as it would increase exponentially the number possibilities, but I haven't thought through it in detail.

I think the easiest way would be to add the label as an empty tag to your assertion result. I know it's not ideal, but for the time being, I don't think I'll be looking into supporting this.  Obviously if a PR comes in that supports in a reasonable way, then great.

Sorry it's not better news.

**Comment by janmeier** [comment]
I understand your concerns about performance, I mostly just wanted to be sure that I didn't miss anything obvious
