### ISSUE TITLE
became fail with Error: You can't print a magicpen instance with a text style

### ISSUE THREAD

**Issue by RusAlex** [bruderstein/unexpected-react#22]
unexpected-react v.0.5.2

Error: You can't print a magicpen instance with a text style

Here is minimal working (failing test) example.

```javascript
/*eslint-env node, mocha */
import React from 'react';
import TestUtils from 'react-addons-test-utils';
import unexpectedReact from 'unexpected-react';
import unexpected from 'unexpected';

const expect = unexpected.clone()
    .use(unexpectedReact);

class Header extends React.Component {

  render() {
    return (
      <div></div>
    )
  }
}

class ComponentFoo extends React.Component {

  render() {
    return (
      <div>
        <Header property={{}}></Header>
      </div>
    )
  }
}


describe('Test component', function() {

  it('Should work', function() {
    let renderer = TestUtils.createRenderer();
    renderer.render(<ComponentFoo />);

    return expect(
      renderer,
      'to have rendered',
      <div>
      </div>
    );
  });

});
```

**Comment by sunesimonsen** [comment]
Hi Alexander, could you write me the stack trace.

**Comment by bruderstein** [comment]
You should update to unexpected-react 3.1.1

0.5.2 has this issue in unexpected-htmllike.  This has been fixed in a newer version.

**Comment by sunesimonsen** [comment]
@bruderstein was the check I did maybe a bit too ruff? I can roll it back if it causes problems. But when most people have upgraded I would like to have this kind of check.

**Comment by bruderstein** [comment]
@RusAlex please let me know when you've upgraded that this error goes away.

Although there are 3 major versions, the only breaking changes are that props & attributes are now tested using `to satisfy` semantics by default, and dropped support for React 0.13, but it looks like you're using at least 0.14, so 3.x will be fine.

**Comment by RusAlex** [comment]
Thanks mates. 

Also would be good to see most recent version in Tags. I thought 0.5.2 is the newest version. And did not even noticed my package.json had a hard lock for unexpected-react@0.5.2 version.
