### ISSUE TITLE
PhantomJS 2.1.1 ReferenceError: Can't find variable: Map

### ISSUE THREAD

**Issue by handane123** [bruderstein/unexpected-react#27]
my unit test can run successfully in the browser, but with phantomjs, it occurs an error below:
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  ReferenceError: Can't find variable: Map
  at C:/Users/handane/Desktop/react/Refactor/tests.webpack.js:46538 <- webpack:///~/react-render-hook/lib/componentMap.js:3:0

**Comment by bruderstein** [comment]
Looks like you'll need a ES6 Map polyfill for PhantomJS - https://www.npmjs.com/package/es6-map and use the `es6-map/implement` version.

Can you let me know if that works?

**Comment by handane123** [comment]
1. npm i -D babel-polyfill
2.the karma config looks like :
        **files: [ 'node_modules/babel-polyfill/dist/polyfill.js'],**
