### ISSUE TITLE
Tests to examine property and state?

### ISSUE THREAD

**Issue by ezmiller** [bruderstein/unexpected-react#29]
I've looked over your library. I like the diff-ing output and the syntax makes is nicely expressive. The ability to use JSX is also great! But comparing this library with airbnb's enzyme, I wondered whether there is a way to examine the setup of the component for example testing for state and prop values and so on. Enzyme has the `state()` and `props` methods...

**Comment by ezmiller** [comment]
Looking a bit more closely I see that one way to do this is just to access for example the props object on the rendered component object returned by `TestUtils.renderIntoDocument`:

```javascript
describe('HelloWorld', () => {
  let component;

  it('should render correctly', () => {
    component = TestUtils.renderIntoDocument(<HelloWorld name={'Sally'} />);            
    expect(component.props, 'to have keys', ['name']);
  });

});
```

That's just fine. I wonder though if it might be a good idea, if possible, to change unexpected-react so that one could use enzyme's `mount` and `shallow` functions, something like a `unexpected-react-enzyme`? That way one could use all those helper functions that enzyme exposes...?

**Comment by bruderstein** [comment]
So in this case `mount` is nothing more than a helper for `TestUtils.renderIntoDocument`? And it's actually pretty much `const mount = TestUtils.renderIntoDocument` (maybe bound to `TestUtils`, not sure).  `shallow` is pretty similar, maybe 2 lines.

Not sure how useful that is?

**Comment by ezmiller** [comment]
Hi @bruderstein just picking this up again. I didn't follow though. You aren't sure how useful what is?

**Comment by bruderstein** [comment]
Ahhhh... 

This is actually available now:

```
expect(<MyComponent />, 
  'when rendered', 
  'with event', 'click', 
  'to have rendered', <button>Clicked once</button>
);
```

Or as a short form if you just want to check the render:
```
expect(<MyComponent />, 
  'to render as',
  <button>Not yet clicked</button>
);
```

Use `'when deeply rendered'` or `'to deeply render as'` to render using the full DOM renderer

**Comment by bruderstein** [comment]
Anything else you'd need?

**Comment by ezmiller** [comment]
Nope, thanks! Curious though what `when rendered` is doing under the hood...
