### ISSUE TITLE
Error in one of the examples on the document frontpage

### ISSUE THREAD

**Issue by sunesimonsen** [bruderstein/unexpected-react#30]
<img width="810" alt="screen shot 2016-11-16 at 23 39 36" src="https://cloud.githubusercontent.com/assets/90802/20368841/13a9fef4-ac56-11e6-84ea-12b199273bf0.png">

**Comment by bruderstein** [comment]
Hmm... I've seen this before somewhere. I'm not sure how I can debug this. I'll have a dig around.

Thanks for the report

**Comment by bruderstein** [comment]
This has now been fixed with some separation of building the docs.
