### ISSUE TITLE
When updating from v3.2.4 to v3.3.0/v3.3.1 asserting on objects with no prototype fails

### ISSUE THREAD

**Issue by eigenmannmartin** [bruderstein/unexpected-react#31]
This case does occurs with deeply nested Objects when there is no __proto__ defined.
```JS
describe('should not use props hasOwnProperty', () => {
    it('should assert a nested array', () => {
        var result = {
            id: '666',
            name: 'Chuck Norris'
        };
        result.__proto__ = null;

        return expect(result, 'to satisfy', {
            attributes: {
                id: '666',
                name: 'Chuck Norris'
            }
        });
    });
});
```

I did some debugging but was unable to figure out where it comes from.
Let me know it I can help in some way.

cheers
Martin

**Comment by bruderstein** [comment]
Sorry, yes, you're right. Apologies. Thanks for reporting.

The issue is here: https://github.com/bruderstein/unexpected-react/blob/master/src/types.js#L119

I'll fix it later today and publish a new version.  I'll also add a test so this can't happen again.

**Comment by eigenmannmartin** [comment]
@bruderstein Thanks very much! btw. awesome work :heart:
