### ISSUE TITLE
Support multiple 'with event' calls

### ISSUE THREAD

**Issue by joelmukuthu** [bruderstein/unexpected-react#34]
With `blur`, you'll want to first call `onFocus` then `onBlur` to be sure that the thing is behaving as expected. 

I tried something like this: 
```js
const renderer = TestUtils.createRenderer();
renderer.render(<Button />);

return expect(
  renderer, 
  'with event focus', 
  'to contain', 
  <button className='focus' />
).then(() => expect(
  renderer, 
  'with event blur', 
  'to contain', 
  <button className='blur' />
));

// or the shorter version:

return expect(
  renderer, 
  'with event focus', 
  'with event blur', 
  'to contain', 
  <button className='blur' />
);
```
which didn't work. But if I triggered the events myself then it worked:
```js
const {
  props: {
    onFocus,
    onBlur
  }
} = renderer.getRenderOutput();

onFocus();
return expect(
  renderer, 
  'to contain', 
  <button className='focus' />
).then(() => {
  onBlur();
  return expect(
    renderer, 
    'to contain', 
    <button className='blur' />
  );
);
```
Did I do something wrong or can this count as a feature request? :)

**Comment by joelmukuthu** [comment]
Upon further investigation, it seems this is a bug in my code. 

At first I couldn't reproduce it, see [this gist](https://gist.github.com/joelmukuthu/deb1f4bd656b4ab51a42440a816ca057/e3266f90f4dcb0afd66ff11de6d6ae34c1192a69). 

But then I was able to, with [this revision of the same gist](https://gist.github.com/joelmukuthu/deb1f4bd656b4ab51a42440a816ca057/343ff32aca51fe30efe7f484f2d465586c59c8b1).

The main difference is the render function:
```js
// works:
render() {
        const {
            focus
        } = this.state;

        return (
            <button 
                 onFocus={this.onFocus} 
                 onBlur={this.onBlur} 
                 className={focus ? 'focus' : 'no-focus'} />
        );
    }
```

```js
// doesn't work

render() {
        const {
            focus
        } = this.state;

        return (
            <div tabIndex='0' onFocus={this.handleFocus} onBlur={this.handleBlur}>
                {focus &&
                    <div className='with-focus'>
                        <span>with focus</span>
                    </div>
                }
            </div>
        );
    }
```
with the main difference being that the one that fails renders a new subtree if the element has focus.

**Comment by bruderstein** [comment]
I've just added the failing version of the gist to the repo regression tests, and all the tests passed. I'll try adding it to a fresh repo with dependencies installed normally.

Could you post the output of the test that fails?

**Comment by joelmukuthu** [comment]
:face_with_head_bandage: I was using an old version of the plugin (v3.1.2). It works fine with v3.3.2. Closing this, sorry for wasting time :)

**Comment by bruderstein** [comment]
No worries! Glad it's sorted. I'll add your test case to the repo anyway,
good to have these sorts of issues validated that they don't return. Thanks
for taking the time to create a repro case.

**Comment by joelmukuthu** [comment]
Great. No worries!
