### ISSUE TITLE
Dynamic Element Names not handled

### ISSUE THREAD

**Issue by bmhardy** [bruderstein/unexpected-react#35]
Using unexpected-react version 3.3.2. When I have a dynamic element name in my JSX, my app handles this fine however the unexpected-react tests fail and indicate the tag as the variable name rather than the variable value. i.e. using the code below, unexpected-react complains that <tag !== <a or <btn

```
    const tags = { 'default': 'a', 'qbo': 'btn' };
    const tagLookup = this.props.theme ? this.props.theme : 'default';
    const tag = tags[tagLookup];

    return (
      <span>
         <tag
             className={styles.pageBackLink}
             href='#'
             onClick={this.props.backControlHandler}
         >
            <LeftChevron />
         </tag>
      </span>
    );
```

**Comment by bruderstein** [comment]
How is your app creating this function - presumably not with JSX. JSX will translate _any_ lowercase tag to it's string equivalent

e.g.
```
<tag className="test />
```

becomes
```
React.createElement('tag', { "className": "test" }, null)
```

And
```
<Tag className="test />
```

becomes
```
React.createElement(Tag, { "className": "test" }, null)
```

Is the code you provided your app code or your test? If your app is working actually converting the `<tag ....` to `React.createElement(tag, ...`, you must have some extra options for Babel (I really don't know how it's possible to do that, so can't tell you where to look).

I'd start by looking at your transpiled source, and see how your app code is being transpiled.

Here's the link to the babel playground where you can see how the JSX is transformed.

http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&experimental=false&loose=false&spec=false&code=function%20MyComponent()%20%7B%0A%20%20%20%20const%20tags%20%3D%20%7B%20'default'%3A%20'a'%2C%20'qbo'%3A%20'btn'%20%7D%3B%0A%20%20%20%20const%20tagLookup%20%3D%20this.props.theme%20%3F%20this.props.theme%20%3A%20'default'%3B%0A%20%20%20%20const%20tag%20%3D%20tags%5BtagLookup%5D%3B%0A%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cspan%3E%0A%20%20%20%20%20%20%20%20%20%3Ctag%0A%20%20%20%20%20%20%20%20%20%20%20%20%20className%3D%7Bstyles.pageBackLink%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20href%3D'%23'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20onClick%3D%7Bthis.props.backControlHandler%7D%0A%20%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CLeftChevron%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%3C%2Ftag%3E%0A%20%20%20%20%20%20%3C%2Fspan%3E%0A%20%20%20%20)%3B%0A%20%20%20%20%0A%7D&playground=true

Let me know how it goes!

**Comment by bruderstein** [comment]
Closing as no feedback.
