### ISSUE TITLE
Update to React16 results in warning of too old React DevTools

### ISSUE THREAD

**Issue by Bjorgvin** [bruderstein/unexpected-react#48]
After updating to React16 our unittests started warning about too old React DevTools with the following message

![image](https://user-images.githubusercontent.com/491852/30921799-e092aa46-a396-11e7-9228-edcc7c8b7f86.png)

This only happens in UnitTests where we `import unexpectedReact from 'unexpected-react'`

**Comment by bruderstein** [comment]
Have you updated to v5.0.0 of unexpected-react?

**Comment by Bjorgvin** [comment]
No, sorry about that. I checked the [releases](https://github.com/bruderstein/unexpected-react/releases) and the latest was v4.1.0 ... should have checked [npm](https://www.npmjs.com/package/unexpected-react) 

Thanks ... I'll update and close the issue if the warning is gone :)

**Comment by Bjorgvin** [comment]
After update to v5.0.0 the warning is gone :) thanks @bruderstein for the information. I'm closing this issue.
