### ISSUE TITLE
Test suite fails with react-dom 16.6.0

### ISSUE THREAD

**Issue by papandreou** [bruderstein/unexpected-react#56]
Upgrading react-dom from 16.5.2 to 16.6.0 makes 83 tests fail when running this part of the test suite:

```
mocha --require babel-core/register src/tests/general/*.spec.js
```

Bisecting in the react repo reveals that it broke when https://github.com/facebook/react/pull/13902 was merged.

**Comment by bruderstein** [comment]
Closing this as 6.0.0 supports 16.9 and above, so this is probably no longer an issue any more.

**Comment by papandreou** [comment]
Awesome! Remember to push the new release :innocent:
